"""Isolated encrypted reversal vault (AGENTS.md/CLAUDE.md 18.0.3).

A separate SQLite file, never `data/app.db` and never ATTACHed to the main
connection, so an ordinary application connection has no path to it at all.
Each subject's original identity bundle is stored as one authenticated-
encryption token (`cryptography.fernet.Fernet`: AES-128-CBC + HMAC-SHA256,
a fresh random IV per encryption, generated by a vetted library rather than
anything hand-rolled here). The table also carries a key-version tag and
plaintext timestamps/subject_id, matching the "ciphertext, nonce/IV, key
version, subject ID, and vault timestamps" scope CLAUDE.md allows.

Access is deliberately narrow: this module exposes `store_identity` (called
by app/privacy/pseudonymise.py while writing an operation plan) and
`retrieve_identity` (decryption -- called only by the authenticated admin
reversal workflow in app/privacy/reverse.py, and by this package's own
crash-recovery path in pseudonymise.py, which needs to rebuild the
verification needle list for an operation it already started and is
resuming, never for a fresh unauthenticated caller). There is no generic
`get_original_identity()` exposed to profile/search/evidence/reasoning
code, and nothing here is ever imported by those modules.
"""

import json
import sqlite3
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken

_KEY_VERSION = "v1"


class VaultError(RuntimeError):
    """The vault could not be read or written. Messages here are generic on
    purpose and must never carry vault plaintext or key material."""


class VaultConfigError(VaultError):
    """PSEUDONYM_VAULT_KEY is missing or not a valid Fernet key. Fails
    closed: a pseudonymisation operation must never proceed by silently
    skipping vault storage or by falling back to storing plaintext."""


@dataclass(frozen=True)
class IdentityBundle:
    """The original identity, reconstructable only by the admin reversal
    workflow. `profile_metadata` is whatever non-identifying-at-rest active
    profile metadata existed at pseudonymisation time, restored verbatim on
    reversal."""

    original_name: str
    original_emails: tuple[str, ...] = ()
    original_aliases: tuple[str, ...] = ()
    profile_metadata: dict = field(default_factory=dict)

    def to_json(self) -> str:
        return json.dumps(
            {
                "original_name": self.original_name,
                "original_emails": list(self.original_emails),
                "original_aliases": list(self.original_aliases),
                "profile_metadata": self.profile_metadata,
            }
        )

    @staticmethod
    def from_json(text: str) -> "IdentityBundle":
        data = json.loads(text)
        return IdentityBundle(
            original_name=data["original_name"],
            original_emails=tuple(data.get("original_emails", [])),
            original_aliases=tuple(data.get("original_aliases", [])),
            profile_metadata=data.get("profile_metadata") or {},
        )


def _fernet(key: str) -> Fernet:
    try:
        return Fernet(key.encode("ascii") if isinstance(key, str) else key)
    except (ValueError, TypeError) as exc:
        raise VaultConfigError("PSEUDONYM_VAULT_KEY is not a valid Fernet key") from exc


def _connect(vault_path: Path) -> sqlite3.Connection:
    vault_path = Path(vault_path)
    vault_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(vault_path))
    conn.row_factory = sqlite3.Row
    conn.execute(
        "CREATE TABLE IF NOT EXISTS vault_entries ("
        " subject_id TEXT PRIMARY KEY,"
        " ciphertext TEXT NOT NULL,"
        " key_version TEXT NOT NULL,"
        " created_at TEXT NOT NULL,"
        " updated_at TEXT NOT NULL"
        ")"
    )
    conn.commit()
    return conn


def store_identity(vault_path: Path, key: str, subject_id: str, bundle: IdentityBundle) -> None:
    """Encrypt and upsert one subject's original identity bundle. Upserting
    (rather than refusing a second write) is what lets re-pseudonymisation
    after an admin reversal reuse the same vault row."""
    if not key:
        raise VaultConfigError("PSEUDONYM_VAULT_KEY is not configured")
    token = _fernet(key).encrypt(bundle.to_json().encode("utf-8")).decode("ascii")
    now = datetime.now(UTC).isoformat()
    conn = _connect(vault_path)
    try:
        conn.execute(
            "INSERT INTO vault_entries "
            "(subject_id, ciphertext, key_version, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?) "
            "ON CONFLICT(subject_id) DO UPDATE SET "
            "ciphertext = excluded.ciphertext, key_version = excluded.key_version, "
            "updated_at = excluded.updated_at",
            (subject_id, token, _KEY_VERSION, now, now),
        )
        conn.commit()
    finally:
        conn.close()


def retrieve_identity(vault_path: Path, key: str, subject_id: str) -> IdentityBundle | None:
    """Decrypt one subject's original identity bundle. Restricted callers
    only -- see module docstring. Returns None if no vault entry exists
    (never invented, never guessed)."""
    if not key:
        raise VaultConfigError("PSEUDONYM_VAULT_KEY is not configured")
    if not Path(vault_path).exists():
        return None
    conn = _connect(vault_path)
    try:
        row = conn.execute(
            "SELECT ciphertext FROM vault_entries WHERE subject_id = ?", (subject_id,)
        ).fetchone()
    finally:
        conn.close()
    if row is None:
        return None
    try:
        plaintext = _fernet(key).decrypt(row["ciphertext"].encode("ascii"))
    except InvalidToken as exc:
        raise VaultError("vault entry could not be decrypted with the configured key") from exc
    return IdentityBundle.from_json(plaintext.decode("utf-8"))


def has_entry(vault_path: Path, subject_id: str) -> bool:
    """Existence check only -- never decrypts, never needs the key. Safe for
    ordinary pseudonymisation-service bookkeeping to call."""
    if not Path(vault_path).exists():
        return False
    conn = _connect(vault_path)
    try:
        return (
            conn.execute(
                "SELECT 1 FROM vault_entries WHERE subject_id = ?", (subject_id,)
            ).fetchone()
            is not None
        )
    finally:
        conn.close()
